const CategoriesActionTypes = {
  GET_TOP_LEVEL_CATEGORIES_START: "GET_TOP_LEVEL_CATEGORIES_START",
  GET_TOP_LEVEL_CATEGORIES_SUCCESS: "GET_TOP_LEVEL_CATEGORIES_SUCCESS",
  GET_TOP_LEVEL_CATEGORIES_FAILURE: "GET_TOP_LEVEL_CATEGORIES_FAILURE",
  GET_CURRENT_CATEGORY_START: "GET_CURRENT_CATEGORY_START",
  GET_CURRENT_CATEGORY_SUCCESS: "GET_CURRENT_CATEGORY_SUCCESS",
  GET_CURRENT_CATEGORY_FAILURE: "GET_CURRENT_CATEGORY_FAILURE",
  GET_SUBCATEGORIES_START: "GET_SUBCATEGORIES_START",
  GET_SUBCATEGORIES_SUCCESS: "GET_SUBCATEGORIES_SUCCESS",
  GET_SUBCATEGORIES_FAILURE: "GET_SUBCATEGORIES_FAILURE",
};

export default CategoriesActionTypes;
